name: Build SmartApps (Reusable)

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  call-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets (masked)
        run: |
          echo "JENKINS_URL=${{ secrets.JENKINS_URL }}"
          echo "JENKINS_USER=${{ secrets.JENKINS_USER }}"
          echo "JENKINS_TOKEN=${{ secrets.JENKINS_TOKEN }}"

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.JENKINS_URL }}" ] || \
             [ -z "${{ secrets.JENKINS_USER }}" ] || \
             [ -z "${{ secrets.JENKINS_TOKEN }}" ]; then
            echo "❌ Missing one or more required secrets: JENKINS_URL, JENKINS_USER, JENKINS_TOKEN"
            exit 1
          fi

      - name: Trigger Jenkins
        run: |
          curl -v -X POST \
            -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/job/${{ inputs.job }}/build"
